// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/79354/leetcode-go/leetcode/testutil"
	"testing"
)

func Test_c(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, minimumCost, "c.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.com/contest/weekly-contest-483/problems/minimum-cost-to-make-two-binary-strings-equal/
// https://leetcode.com/problems/minimum-cost-to-make-two-binary-strings-equal/
