// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/79354/leetcode-go/leetcode/testutil"
	"testing"
)

func Test_b(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, wordSquares, "b.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.com/contest/weekly-contest-483/problems/word-squares-ii/
// https://leetcode.com/problems/word-squares-ii/
