// Generated by copypasta/template/leetcode/generator_test.go
package main

import (
	"github.com/79354/leetcode-go/leetcode/testutil"
	"testing"
)

func Test_d(t *testing.T) {
	if err := testutil.RunLeetCodeFuncWithFile(t, minMergeCost, "d.txt", 0); err != nil {
		t.Fatal(err)
	}
}
// https://leetcode.com/contest/weekly-contest-483/problems/minimum-cost-to-merge-sorted-lists/
// https://leetcode.com/problems/minimum-cost-to-merge-sorted-lists/
